### ISSUE TITLE
Can't run ACLr8

### ISSUE THREAD

**Issue by HiredGunn** [fletom/ACLr8#1]
I downloaded this file to get rid of dozens of "ACL found but not expected" results while trying to repair disk permissions on my 27" iMac (2010), running Mavericks 10.9.5. 

When I clicked on the download, a terminal window opened, asking for my password. I don't have a password on this computer and it did not specify what it wanted to open using a password. I tried a couple of my common passwords, but after three tries, it closed.

I've tried this several times now, redownloading, using a variety of possible passwords, etc., but always with the same result. 

Any idea what I'm doing wrong?

**Comment by fletom** [comment]
Hi @HiredGunn. You can't use ACLr8 without a password because the `sudo` command it uses requires a password to be entered. What you can do is temporarily set a password for your computer, and then disabled it after ACLr8 finishes executing.
