### ISSUE TITLE
chmod version might not be correct

### ISSUE THREAD

**Issue by samypr100** [fletom/ACLr8#2]
If multiple chmod are installed it might become an issue. To ensure the correct chmod is being used, wouln't it be good practice to change chmod to /bin/chmod?

**Comment by Seacidal** [comment]
Maybe this is partially behind the trouble I'm having with ACLr8? It runs fine but does not clean up the ACL issues.

**Comment by fletom** [comment]
Hey, it probably should be `/bin/chmod` but I've never seen more than one chmod installed on a machine. Is there any particular case you've come across where it's causing problems?

**Comment by samypr100** [comment]
@fletom 
I forgot since I wrote this so long ago, but for example in Mac if you're using a `brew` installed `chmod` which is `gnu` compliant
